
[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.release]
cmds = ["python manage.py migrate --noinput", "python manage.py collectstatic --noinput"]

[phases.start]
cmd = "gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 4"
