"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# myproject/settings.py
import dj_database_url
import os
import sys
from pathlib import Path
from decouple import config, Csv

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================
# БЕЗОПАСНОСТЬ
# ============================================
SECRET_KEY = config('SECRET_KEY', default='django-insecure-temp-key-for-dev')
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# ============================================
# ПРИЛОЖЕНИЯ
# ============================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
    'telegram_bot',
]

# ============================================
# MIDDLEWARE (порядок важен!)
# ============================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',         # безопасность (HTTPS, XSS защита)
    'whitenoise.middleware.WhiteNoiseMiddleware',            # Должен быть сразу после SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',  # работа с сессиями
    'django.middleware.common.CommonMiddleware',             # общие вещи (редиректы, просмотры)
    'django.middleware.csrf.CsrfViewMiddleware',              # защита от CRSF  атак
    'django.contrib.auth.middleware.AuthenticationMiddleware',# аутентификация пользователя
    'django.contrib.messages.middleware.MessageMiddleware',    # система сообщений
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # защита от clickjacking атак
    'shop.middleware.RequestLoggingMiddleware',                 # Кастомные middleware
]

ROOT_URLCONF = 'myproject.urls'

# ============================================
# ШАБЛОНЫ
# ============================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],                             # Можно оставить пустым
        'APP_DIRS': True,                       # Это важно! Должно быть True
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.shop_context',
                'shop.context_processors.support_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# ============================================
# БАЗА ДАННЫХ (АВТОМАТИЧЕСКИЙ ВЫБОР)
# ============================================
# Получаем DATABASE_URL из переменных окружения (Railway)
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Настройка для Railway PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DATABASE_NAME', default='railway'),
            'USER': config('DATABASE_USER', default='postgres'),
            'PASSWORD': config('DATABASE_PASSWORD', default=''),
            'HOST': config('DATABASE_HOST', default='postgres.railway.internal'),
            'PORT': config('DATABASE_PORT', default='5432'),
            'CONN_MAX_AGE': 0,
            'OPTIONS': {
                'sslmode': 'disable',  # Временно для теста
                'connect_timeout': 10,
            },
        }
    }
    print("✅ Connected to PostgreSQL on Railway")
else:
    # Локальная разработка - SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    print("✅ Using SQLite for local development")

# ============================================
# ВАЛИДАЦИЯ ПАРОЛЕЙ
# ============================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================================
# ИНТЕРНАЦИОНАЛИЗАЦИЯ
# ============================================
LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True

# ============================================
# СТАТИЧЕСКИЕ ФАЙЛЫ (для Whitenoise)
# ============================================
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'shop' / 'static']  # ОКСАНА Добавила эту строку
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ============================================
# МЕДИА ФАЙЛЫ
# ============================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================
# АУТЕНТИФИКАЦИЯ
# ============================================
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

# ============================================
# СЕССИИ
# ============================================
SESSION_COOKIE_AGE = 1209600
SESSION_COOKIE_SECURE = not DEBUG  # True в продакшене, False в разработке
SESSION_COOKIE_NAME = 'sessionid'

# ============================================
# CSRF
# ============================================
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

# ============================================
# TELEGRAM БОТ
# ============================================
TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')
TELEGRAM_BOT_USERNAME = config('TELEGRAM_BOT_USERNAME', default='')
TELEGRAM_ADMIN_IDS = config('TELEGRAM_ADMIN_IDS', default='', cast=Csv())

# ============================================
# ПРОЧЕЕ
# ============================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# ЛОГИРОВАНИЕ
# ============================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
# В ТЕРМИНАЛЕ:
# python manage.py makemigrations
# python manage.py migrate
# python manage.py makemigrations telegram_bot
# python manage.py migrate
