"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# myproject/settings.py
import dj_database_url
import os
import sys
from pathlib import Path
from decouple import config, Csv

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================
# БЕЗОПАСНОСТЬ
# ============================================
SECRET_KEY = config('SECRET_KEY', default='django-insecure-temp-key-for-dev')
DEBUG = config('DEBUG', default=False, cast=bool) # ВАЖНО: DEBUG всегда False в продакшене
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# ============================================
# ДОПОЛНИТЕЛЬНЫЕ НАСТРОЙКИ БЕЗОПАСНОСТИ
# ============================================

# 🔐 Защита от XSS-атак
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# 🔐 Перенаправление HTTP -> HTTPS
SECURE_SSL_REDIRECT = not DEBUG  # True в продакшене

# 🔐 HSTS (HTTP Strict Transport Security)
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 год
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

# 🔐 Cookie только через HTTPS
SESSION_COOKIE_SECURE = not DEBUG  # True в продакшене
CSRF_COOKIE_SECURE = not DEBUG     # True в продакшене

# 🔐 Защита сессий
SESSION_COOKIE_HTTPONLY = True  # JavaScript не может читать cookie
CSRF_COOKIE_HTTPONLY = True  # Защита от CSRF

# 🔐 Защита от CSRF через SameSite
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# 🔐 Защита от clickjacking
X_FRAME_OPTIONS = 'DENY'

# 🔐 Ограничение размера запросов (защита от DoS)
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5 MB


# 🔐 Количество попыток входа (защита от bruteforce)
# Требуется django-axes (pip install django-axes)
# AXES_FAILURE_LIMIT = 5
# AXES_COOLOFF_TIME = 1  # часы

# 🔐 Безопасные заголовки
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ============================================
# ЛОГИРОВАНИЕ
# ============================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        # Вывод в консоль (Railway собирает логи из stdout)
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'stream': 'ext://sys.stdout',
        },
        # Файл для локальной разработки
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
            'mode': 'a',
            'maxBytes': 10485760,  # 10 MB
            'backupCount': 5,
        },
    },
    'loggers': {
        # Логи Django
        'django': {
            'handlers': ['console', 'file'] if DEBUG else ['console'],
            'level': 'INFO' if DEBUG else 'WARNING',
            'propagate': False,
        },
        # Безопасность
        'django.security': {
            'handlers': ['console', 'file'] if DEBUG else ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Ошибки запросов
        'django.request': {
            'handlers': ['console', 'file'] if DEBUG else ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Ваше приложение
        'shop': {
            'handlers': ['console', 'file'] if DEBUG else ['console'],
            'level': 'INFO' if DEBUG else 'WARNING',
            'propagate': False,
        },
        # Telegram бот
        'telegram_bot': {
            'handlers': ['console', 'file'] if DEBUG else ['console'],
            'level': 'INFO' if DEBUG else 'WARNING',
            'propagate': False,
        },
    },
    # Корневой логгер
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}


# ============================================
# ПРИЛОЖЕНИЯ
# ============================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
    'telegram_bot',
]

# ============================================
# MIDDLEWARE (порядок важен!)
# ============================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',         # безопасность (HTTPS, XSS защита)
    'whitenoise.middleware.WhiteNoiseMiddleware',            # Должен быть сразу после SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',  # работа с сессиями
    'django.middleware.common.CommonMiddleware',             # общие вещи (редиректы, просмотры)
    'django.middleware.csrf.CsrfViewMiddleware',              # защита от CRSF  атак
    'django.contrib.auth.middleware.AuthenticationMiddleware',# аутентификация пользователя
    'django.contrib.messages.middleware.MessageMiddleware',    # система сообщений
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # защита от clickjacking атак
    'shop.middleware.RequestLoggingMiddleware',                 # Кастомные middleware
]

ROOT_URLCONF = 'myproject.urls'

# ============================================
# ШАБЛОНЫ
# ============================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],                             # Можно оставить пустым
        'APP_DIRS': True,                       # Это важно! Должно быть True
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.shop_context',
                'shop.context_processors.support_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'
ASGI_APPLICATION = 'myproject.asgi.application'

# ============================================
# БАЗА ДАННЫХ (АВТОМАТИЧЕСКИЙ ВЫБОР)
# ============================================
# Получаем DATABASE_URL из переменных окружения (Railway)
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Настройка для Railway PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DATABASE_NAME', default='railway'),
            'USER': config('DATABASE_USER', default='postgres'),
            'PASSWORD': config('DATABASE_PASSWORD', default=''),
            'HOST': config('DATABASE_HOST', default='postgres.railway.internal'),
            'PORT': config('DATABASE_PORT', default='5432'),
            'CONN_MAX_AGE': 0,
            'OPTIONS': {
                'sslmode': 'disable',  # Временно для теста
                'connect_timeout': 10,
            },
        }
    }
    print("✅ Connected to PostgreSQL on Railway")
else:
    # Локальная разработка - SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    print("✅ Using SQLite for local development")

# ============================================
# ВАЛИДАЦИЯ ПАРОЛЕЙ
# ============================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================================
# ИНТЕРНАЦИОНАЛИЗАЦИЯ
# ============================================
LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True

# ============================================
# СТАТИЧЕСКИЕ ФАЙЛЫ (для Whitenoise)
# ============================================
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'shop' / 'static']  # ОКСАНА Добавила эту строку
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ============================================
# МЕДИА ФАЙЛЫ
# ============================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================
# АУТЕНТИФИКАЦИЯ
# ============================================
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

# ============================================
# СЕССИИ
# ============================================
SESSION_COOKIE_AGE = 1209600
SESSION_COOKIE_SECURE = not DEBUG  # True в продакшене, False в разработке
SESSION_COOKIE_NAME = 'sessionid'

# ============================================
# CSRF
# ============================================
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

# ============================================
# TELEGRAM БОТ
# ============================================
TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')
TELEGRAM_BOT_USERNAME = config('TELEGRAM_BOT_USERNAME', default='')
TELEGRAM_ADMIN_IDS = config('TELEGRAM_ADMIN_IDS', default='', cast=Csv())

# ============================================
# ПРОЧЕЕ
# ============================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# ЛОГИРОВАНИЕ
# ============================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
# В ТЕРМИНАЛЕ:
# python manage.py makemigrations
# python manage.py migrate
# python manage.py makemigrations telegram_bot
# python manage.py migrate
