# Generated by Django 6.0.2 on 2026-03-08 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_supportticket_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('default_address', models.TextField(blank=True, help_text='Адрес доставки по умолчанию', null=True, verbose_name='Адрес доставки')),
                ('avatar', models.ImageField(blank=True, help_text='Загрузите ваше фото (до 2 МБ, форматы: JPG, PNG)', null=True, upload_to='avatars/', verbose_name='Фотография профиля')),
                ('bio', models.TextField(blank=True, help_text='Расскажите немного о себе', max_length=500, null=True, verbose_name='О себе')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Получать email-уведомления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания профиля')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'db_table': 'user_profiles',
            },
        ),
    ]
