# Generated by Django 6.0.2 on 2026-04-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('question', 'Вопрос'), ('complant', 'Жалоба'), ('suggestion', 'Предложение'), ('technical', 'Техническая проблема'), ('other', 'Другое')], default='question', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('low', 'низкий'), ('medium', 'средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=20, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('new', 'Новые'), ('in_progress', 'В работе'), ('resolved', 'Решено'), ('closed', 'Закрыто')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
