# Generated by Django 6.0.2 on 2026-04-17 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_preorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Предзаказ', 'verbose_name_plural': 'Предзаказы'},
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='preferred_delivery_date',
        ),
        migrations.AlterField(
            model_name='preorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработан'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorders', to='shop.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
