# Generated by Django 6.0.2 on 2026-04-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_telegramlinkcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramlinkcode',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Ожидает'), ('confirmed', '✅ Подтверждён'), ('expired', '⌛ Истёк')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
